# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 28dd43f5cd86f0273e29180ae6b6ba3eaf6cb4a7e197feef051e787e0c4325458f4fe9b10d5ee7f1d36fc7bbdd54e23244afba0a3f43f9167842ed1d36ed84ed

test:
  secret_key_base: acd57ed4e52d8845f31f77eeea1f53c038f858219195f7f5dce99cf41c930164c33ac93239ccf32bd5be0f2390cf3183b6168b7b451c0503ef51333e05d86171

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
